using Xunit;
using FluentAssertions;

namespace SentraUnitTests;

/// <summary>
/// Sample unit test class to get started
/// Generated by Test Project Generator
/// </summary>
public class SampleUnitTest
{
    [Fact]
    public void SampleTest_ShouldPass()
    {
        // Arrange
        var expected = true;
        
        // Act
        var actual = true;
        
        // Assert
        actual.Should().Be(expected);
    }

    [Theory]
    [InlineData(1, 2, 3)]
    [InlineData(10, 20, 30)]
    [InlineData(-1, 1, 0)]
    public void Add_ShouldReturnCorrectSum(int a, int b, int expected)
    {
        // Arrange & Act
        var result = a + b;
        
        // Assert
        result.Should().Be(expected);
    }
}